# yaml
name: master-classes
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.14.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - jupyterlab=4.2.4
  - notebook=7.2.2
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - nbformat=5.10.4
  - tqdm=4.66.5
  - statsmodels=0.14.2
  - pyarrow=17.0.0
  - openpyxl=3.1.5
  - category_encoders=2.6.4
  - feature_engine=1.8.2
  - plotly=5.24.0
  - yellowbrick=1.5
  - scikit-learn=1.5.2
  - xgboost=2.1.1
  - lightgbm=4.5.0
  - catboost=1.2.5
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - tensorflow=2.17.0
  - shap=0.46.0
  - eli5=0.13.0
  - ydata-profiling>=4.6,<5
  - pytest
  - black
  - ruff
  - mypy
  - pip:
    - ipykernel==6.29.5 # keep if you must pin pip-installed ipykernel (avoid duplicating)
    - ydata-profiling>=4.6,<5 # if only available via pip